### ISSUE TITLE
"context" ignored: http://grounding.indra.bio/ground and localhost installation behaving differently wrt context

### ISSUE THREAD

**Issue by hughsalamon** [gyorilab/gilda#136]
curl -X POST -H "Content-Type: application/json" -d '{"text": "TF"}' http://grounding.indra.bio/ground
and
curl -X POST -H "Content-Type: application/json" -d '{"text": "TF", "context":"There is a strong relationship between tissue factor (TF) and cancer"}' http://grounding.indra.bio/ground
return different results, as expected, and quite reasonably help resolve the second query to gene F3.

However, in the latest code (v1.1.0) running locally these queries give the same output:
curl -X POST -H "Content-Type: application/json" -d '{"text": "TF"}' http://localhost:8001/ground
and
curl -X POST -H "Content-Type: application/json" -d '{"text": "TF", "context":"There is a strong relationship between tissue factor (TF) and cancer"}' http://localhost:8001/ground
The output does make it seem that the context is being ignored. Similarly for calls from python code.

Should this not work with a fresh install? Or is something else needed such as grounding terms that require updating? (Really like gilda, but the context sensitivity is a must for disambiguating terms!)

**Comment by bgyori** [comment]
Thanks @hughsalamon! The disambiguation models in Gilda are learned for specific ambiguous strings like `ER`. There are currently models for 1008 such strings (many of these were chosen based on frequency in literature). You can get the list of models like this:
```
curl -X 'GET' 'http://grounding.indra.bio/models' -H 'accept: application/json'
```

It looks like `TF` is not in the list so Gilda doesn't have a model built in for that. We could try to make one though.

**Comment by hughsalamon** [comment]
Thanks @bgyori ! Please note that at Indra.bio gilda **_does_** resolve TF to F3 correctly given the context string (as below)! The issue is that this behavior is different for gilda.app installed locally. Should gilda.app behave the same locally or accessed at grounding.indra.bio?

curl -X POST -H "Content-Type: application/json" -d '{"text": "TF"}' http://grounding.indra.bio/ground
and
curl -X POST -H "Content-Type: application/json" -d '{"text": "TF", "context":"There is a strong relationship between tissue factor (TF) and cancer"}' http://grounding.indra.bio/ground
return different results, as expected, and quite reasonably help resolve the second query to gene F3.

**Comment by hughsalamon** [comment]
For example, we borrowed the "ground IR with context implying the insulin receptor sense" example from your introduction at https://github.com/gyorilab/gilda/blob/master/notebooks/gilda_introduction.ipynb, but this fails for the _**local**_ installation. We have installed on three platforms, and tired multiple gilda versions, and the ignored context issue persists for all local installations.

**Comment by bgyori** [comment]
Oh I'm sorry, I was confused! `TF` is, in fact available, as a model from [Adeft](https://github.com/gyorilab/adeft), another one of our projects which is integrated with Gilda. (The model list I linked to above only includes models made directly by Gilda, not ones imported from Adeft which is why I was confused).

When I run your example locally, I get:


```python
In [7]: import gilda

In [8]: gilda.ground('TF', context='There is a strong relationship between tissue factor (TF) and cancer')
INFO: [2024-03-12 19:43:57] gilda.grounder - Running Adeft disambiguation for TF
Out[8]: 
[ScoredMatch(Term(tf,TF,HGNC,3541,F3,synonym,hgnc,9606,None,None),0.5555555555555556,Match(query=TF,ref=TF,exact=True,space_mismatch=False,dash_mismatches={},cap_combos=[]),disambiguation={"type": "adeft", "score": 1.0, "match": "grounded"}),
 ScoredMatch(Term(tf,TF,HGNC,11740,TF,name,hgnc,9606,None,None),0.0,Match(query=TF,ref=TF,exact=True,space_mismatch=False,dash_mismatches={},cap_combos=[]),disambiguation={"type": "adeft", "score": 0.0, "match": "grounded"}),
 ...]
```
which is the expected result.

It's likely that there is an issue with your installation of Adeft. Could you try
```shell
pip install adeft
python -m adeft.download
```
to make sure you have it installed along with its disambiguation models?

**Comment by hughsalamon** [comment]
Thank you! That is exactly what was needed. adeft was not working and that context evaluation was failing silently. Once the adeft models are there, this works well!
