### ISSUE TITLE
indra/gilda incompatible dependencies

### ISSUE THREAD

**Issue by jim-sheldon** [gyorilab/gilda#137]
indra depends on [markupsafe<2.1.0](https://github.com/sorgerlab/indra/blob/master/setup.py#L15C22-L15C39)

gilda depends on [flask>=3.0](https://github.com/gyorilab/gilda/blob/master/setup.py#L38C61-L38C71) depends on [Werkzeug>=3.0.0](https://github.com/pallets/flask/blob/3.0.0/pyproject.toml#L23C5-L23C22) depends on [MarkupSafe>=2.1.1](https://github.com/pallets/werkzeug/blob/3.0.0/pyproject.toml#L22C18-L22C35)

short-term workaround: use gilda < 1.1.0

long-term recommendation: automated nightly integration smoke tests

**Comment by bgyori** [comment]
This is indeed an apparent conflict, though in practice, gilda works without issues with markupsafe==2.0.1, and also, even in INDRA, this is only a potential issue if one wants to run its REST API locally which is not common. I am looking into solving this by changing the dependency structure in INDRA, but still, I don't think this is causing any practical issues.

**Comment by bgyori** [comment]
Fixed in https://github.com/sorgerlab/indra/pull/1440
